tiddlywiki.com / beta: deprecated uploaddav script
Uploading via DAV is no longer supported.
These script are not being maintained and do not satisfy all
requirements of the release process.

git-svn-id: http://svn.tiddlywiki.org/Trunk@10146 bb0f57cd-c710-0410-a8fb-e8bc1be0d679

diff --git a/verticals/beta/uploaddavbeta b/verticals/beta/uploaddavbeta
--- a/verticals/beta/uploaddavbeta
+++ b/verticals/beta/uploaddavbeta
@@ -1,7 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Usage:
 #  uploadbeta [release] [cleanup]
+
+# deprecated
+echo "ERROR: DAV uploading deprecated - use SSH upload script instead."
+exit 1
 
 # default values
 DEFAULT_RELEASE="2.5.2.B1"
